# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jan-Paul Koudstaal – Design Director & Designer
email: hi@jpkoudstaal.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Design Director & Designer working at BLiS in The Netherlands. I enjoy good coffee, riding my bike to work, basketball and comic books.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jpkoudstaal.com" # the base hostname & protocol for your site
twitter_username: jpkoudstaal

# Build settings
markdown: kramdown
